name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: npm -v
    - run: node -v
    - run: npm install
    - run: npm run eslint
    - run: npm test
      if: matrix.os == 'windows-latest'
    - run: npm run test-cov
      if: matrix.os == 'ubuntu-latest'
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      if: matrix.os == 'ubuntu-latest'
      with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info # optional (default value)
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      if: matrix.os == 'ubuntu-latest'
      with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
